common: &common_settings
  patch_size: &patch_size 16
  tubelet_size: &tubelet_size 2
  crop_size: &crop_size 384
  nclips: 1
  fpcs: &fpcs 16

app: probe

logging:
  progress_type: table
  save_csv: true
  save_batch_csv: true
  save_epoch_csv: true

loader_setup: &loader_settings
  num_workers: 4
  persistent_workers: true
  pin_mem: true

train:
  <<: *common_settings
  <<: *loader_settings
  batch_size: 8
  allow_clip_overlap: true
  random_jiggle: true
  train_fraction: 0.85
  val_fraction: 0.15
  datasets:
  - name: "carla"
    path: "./csv_metadata/probe/Carla_recording_20251025_142727_best_spatial.csv"
    fps: 4
  - name: "carla"
    path: "./csv_metadata/probe/Carla_recording_20260116_213318_extra_spatial.csv"
    fps: 4
  - name: "carla"
    path: "./csv_metadata/probe/Carla_recording_20260204_090029_spatial.csv"
    fps: 4
  - name: "carla"
    path: "./csv_metadata/probe/Carla_recording_20260317_205100_best_spatial.csv"
    fps: 4
  - name: "carla"
    path: "./csv_metadata/probe/Carla_recording_20260317_214033_spatial.csv"
    fps: 4
  - name: "carla"
    path: "./csv_metadata/probe/Carla_recording_20260317_233603_spatial.csv"
    fps: 4
  - name: "carla"
    path: "./csv_metadata/probe/Carla_recording_20260318_083409_best_spatial.csv"
    fps: 4
    

data_aug:
  auto_augment: false
  horizontal_flip: false
  motion_shift: false
  random_resize_aspect_ratio:
  - 1.0
  - 1.0
  random_resize_scale:
  - 1.0
  - 1.0
  reprob: 0.0

meta:
  dtype: bfloat16
  save_every_freq: 5
  save_root_dir: ./Experiment
  seed: 239
  sync_gc: true
  continue_train: false
  continue_from_run: null
  resume_prefer_best: true

model:
  compile: false
  common: &common_model
    use_sdpa: true

  enc:
    <<: *common_settings
    name: vjepa2_1_vit_base_384
    load_from: facebookresearch/vjepa2
    source: github
    use_activation_checkpointing: true

  probe:
    name: "EfficientProbe"
    output_dim: 2
    hidden_dim: null
    max_frames: *fpcs
    tubelet_size: *tubelet_size
    num_heads: 8
    num_queries: 32
    depth: 2
    mlp_ratio: 4.0
    init_std: 0.04
    qkv_bias: true
    dropout: 0.15
    use_activation_checkpointing: true
    init_scales: null
    init_shifts: null

optimization:
  anneal: 5
  epochs: 40
  final_lr: 0.0
  final_weight_decay: 0.04
  ipe: 100
  lr: 0.000105
  start_lr: 0.000075
  warmup: 5
  weight_decay: 0.04  
  gradient_optimizer:
    type: normal
    params: 
      reduction: mean

loss:
  enable_velocity: true
  enable_steer: true
  enable_lateral_error: false
  velocity_loss: log_cosh
  steer_loss: log_cosh
  lateral_error_loss: mae
  velocity_idx: 0
  steer_idx: 1
  lateral_error_idx: 2
  velocity_log_var: 0.0
  steer_log_var: 0.0
  lateral_error_log_var: 0.0
  reduction: mean
