app: straightening

common: &common_settings
  patch_size: 16
  tubelet_size: 2
  crop_size: 256
  fpcs: 12


train:
  <<: *common_settings
  batch_size: 16
  num_workers: 4
  persistent_workers: true
  pin_mem: true
  datasets_path:
    - ./../Autonomous_Dataset/carla/LAWM/recording_20251025_142727_best_spatial/
    - ./../Autonomous_Dataset/carla/LAWM/recording_20260204_010805_spatial/
    - ./../Autonomous_Dataset/carla/LAWM/recording_20260308_212005_spatial/
    - ./../Autonomous_Dataset/carla/LAWM/recording_20260317_214033_best_spatial/
    - ./../Autonomous_Dataset/carla/LAWM/recording_20260317_233603_spatial/
    - ./../Autonomous_Dataset/carla/LAWM/recording_20260318_083409_best_spatial/
    - ./../Autonomous_Dataset/carla/LAWM/recording_20260323_200940_best_spatial/
    - ./../Autonomous_Dataset/carla/LAWM/recording_20260329_233141_best_spatial/
    - ./../Autonomous_Dataset/carla/LAWM/recording_20260323_204100_best_spatial/
    - ./../Autonomous_Dataset/carla/LAWM/recording_20260323_210357_best_spatial/
    - ./../Autonomous_Dataset/carla/LAWM/recording_20260329_164940_best_spatial/

data_aug:
  auto_augment: false
  horizontal_flip: false
  motion_shift: false
  random_resize_aspect_ratio:
  - 0.75
  - 1.35
  random_resize_scale:
  - 1.777
  - 1.777
  reprob: 0.0
  normalize: 
  - [0.485, 0.456, 0.406]
  - [0.229, 0.224, 0.225]


model: 
  compile: false
  common: &common_model
    action_pframe: 1
    use_sdpa: true
    use_rope: true
    use_activation_checkpointing: true

  enc: 
    <<: *common_settings
    <<: *common_model
    name: vjepa2_1_vit_base_384
    load_from: /home/alterraonix/.cache/torch/hub/facebookresearch_vjepa2_main
    source: local

  filter:
    <<: *common_settings
    <<: *common_model
    name: TransformerStraightener
    filter_dim: 768
    depth: 2
    num_heads: 12
    mlp_ratio: 4.0
    qkv_bias: true
    qk_scale: null
    drop_rate: 0.0
    attn_drop_rate: 0.0
    drop_path_rate: 0.0
    init_std: 0.02
    uniform_power: false
    use_silu: true
    wide_silu: true

  pred:
    <<: *common_settings
    <<: *common_model
    pred_embed_dim: 512
    depth: 6
    num_heads: 8
    mlp_ratio: 4.0
    qkv_bias: true
    drop_rate: 0.0
    attn_drop_rate: 0.0
    drop_path_rate: 0.0
    init_std: 0.02
    use_silu: true
    wide_silu: true
    is_frame_causal: true

  action:
    <<: *common_settings
    <<: *common_model
    action_embed_dim: 128
    depth: 6
    num_heads: 8
    mlp_ratio: 4.0
    qkv_bias: true
    drop_rate: 0.0
    attn_drop_rate: 0.0
    drop_path_rate: 0.0
    init_std: 0.02
    use_silu: true
    wide_silu: true
    use_activation_checkpointing: true

optimization:
  ema:
    - 0.99925
    - 0.99925
  anneal: 30
  epochs: 50
  warmup: 10
  final_lr: 0.0
  final_weight_decay: 0.015
  ipe: 150
  lr: 0.000125
  start_lr: 4.5e-05
  weight_decay: 0.04

loss:
  auto_steps: 2
  loss_exp: 2.0
  normalize_reps: false
  normalize_actions: false
  reg_name: sigreg
  weight: 1.0
  num_proj: 512
  samp_range: [-5.0, 5.0]
  samp_sz: 16
  lcurve: 0.1

meta:
  dtype: bfloat16
  save_every_freq: 5
  seed: 239
  sync_gc: true

checkpoint:
  patience: 10
  min_delta: 0.0005

logging:
  progress_type: table
  save_csv: true
  save_batch_csv: true
  save_epoch_csv: true
  log_batch_tensorboard: true
  log_model_graph: true
