[TrafficManager]
excluded_junctions = [683, 560, 408, 416, 636, 455, 706, 691, 644, 399, 674, 295]

[MapRender]
rect_dim   = [4, 3]
map_offset = [100, 100]
map_range  = [50, 50]
map_resize = [200, 200]
map_scale  = 3

[PathOptimizer]
path_step = 2
exclude_params = [322.5, -195.5, 19.0]

[RandPath]
min_distant_node = 20
max_distant_node = 500
path_iter = 2

[GPS]
mean_delay = 550
stddev_delay = 200
lat_stddev = 1.0
lon_stddev = 1.5
frequency  = 10

[UI]
alpha       = 0.05  
font_size   = 12
text_height = 20
line_h = 20
bar_w  = 150
bar_h  = 10
font_name = "jetbrainsmononerdfontpropo"

[Offsets]
front_vehicle_offset = 1.5
temporal_offset      = [0.0, 0.15, 0.3, 0.45, 0.6, 0.75]
spatial_offset       = [0, 1, 3, 5, 7, 9]
scout_offset_params  = [-18, 33, 2]

[Vehicle]
decay = 0.2
steer_multiplier = 1.2

    [Vehicle.Physics]
    max_steer  = 70
    wheelbase = 3.047080078125

    [Vehicle.ControlFilter]
    fs = 2.0
    x0 = 2

    [Vehicle.VelocityRegulator]
    Kp = 0.1
    Ki = 0.05
    Kd = 0.05

[Picture]
quality = 90
