common: &common_settings
  patch_size: 16
  tubelet_size: 2
  crop_size: 224
  nclips: 1
  ctx_fpcs: 8
  pred_fpcs: 8

app: action

loader_setup: &loader_settings
  num_workers: 4
  persistent_workers: true
  pin_mem: true

train:
  <<: *common_settings
  <<: *loader_settings
  batch_size: 2
  allow_clip_overlap: true
  random_jiggle: true
  datasets:
    - name: "carla"
      path: "./csv_metadata/action/Carla_recording_20251019_161905_best_spatial.csv"
      fps: 2
    - name: "carla"
      path: "./csv_metadata/action/Carla_recording_20251025_142727_best_spatial.csv"
      fps: 2
    - name: "carla"
      path: "./csv_metadata/action/Carla_recording_20260204_005321_spatial.csv"
      fps: 2
    - name: "carla"
      path: "./csv_metadata/action/Carla_recording_20260204_010805_spatial.csv"
      fps: 2
    - name: "carla"
      path: "./csv_metadata/action/Carla_recording_20260204_085306_spatial.csv"
      fps: 2
    - name: "carla"
      path: "./csv_metadata/action/Carla_recording_20260204_090029_spatial.csv"
      fps: 2
    - name: "carla"
      path: "./csv_metadata/action/Carla_recording_20260312_163316_spatial.csv"
      fps: 2
    - name: "carla"
      path: "./csv_metadata/action/Carla_recording_20260312_164439_spatial.csv"
      fps: 2
    - name: "carla"
      path: "./csv_metadata/action/Carla_recording_20260312_170731_spatial.csv"
      fps: 2

val:
  <<: *common_settings
  <<: *loader_settings
  batch_size: 8
  allow_clip_overlap: true
  random_jiggle: false
  datasets:
    - name: "bdd100k"
      path: "/mnt/HyperStorage_ntfs/Coding/Autonomous/model/JEPA_ACT/data_bdd100k.csv"
      ctx_fpcs: 16
      pred_fpcs: 8

data_aug:
  auto_augment: false
  horizontal_flip: false
  motion_shift: false
  random_resize_aspect_ratio:
  - 0.75
  - 1.35
  random_resize_scale:
  - 1.777
  - 1.777
  reprob: 0.0

meta:
  dtype: bfloat16
  save_every_freq: 5
  seed: 239
  sync_gc: true

model: 
  compile: false
  common: &common_model
    action_pframe: 1
    action_embed_dim: 512
    use_sdpa: true

  enc: 
    <<: *common_settings
    name: vjepa2_vit_large
    load_from: facebookresearch/vjepa2
    use_activation_checkpointing: true


  pred:
    <<: *common_settings
    <<: *common_model
    pred_embed_dim: 1024
    depth: 6
    num_heads: 16
    mlp_ratio: 4.0
    qkv_bias: true
    drop_rate: 0.0
    attn_drop_rate: 0.0
    drop_path_rate: 0.0
    init_std: 0.02
    use_silu: true
    wide_silu: true
    is_frame_causal: true
    use_activation_checkpointing: true
    use_rope: true


  action:
    <<: *common_settings
    <<: *common_model
    depth: 8
    num_heads: 16
    mlp_ratio: 4.0
    qkv_bias: true
    drop_rate: 0.0
    attn_drop_rate: 0.0
    drop_path_rate: 0.0
    init_std: 0.02
    use_silu: true
    wide_silu: true
    use_activation_checkpointing: true
    use_rope: true

optimization:
  anneal: 15
  epochs: 20
  final_lr: 0.0
  final_weight_decay: 0.04
  ipe: 1600
  lr: 0.000425
  start_lr: 0.000075
  warmup: 15
  weight_decay: 0.04

loss:
  auto_steps: 2
  loss_exp: 1.0
  normalize_reps: true
  reg_coeff: 0.0
  l2: 1.0
  l1: 0.02
  lv: 0.1
  lc: 0.01  # Increased from 0.001 to 0.01 (10x higher)
  lm: 0.1